
services:

  # database service
  db:
    image: postgres
    container_name: pulsar-postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pulsar-db-ps
      POSTGRES_DB: postgres
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
      - "host.docker.internal:host-gateway"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  # application service
  panel:
    build: "./"
    container_name: pulsar
    restart: always
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    links:
      - pulsar-postgres
    environment:
      ACCESS_TOKEN: g4rren-dansukdfrang
      POOL_TOKEN: g4rren-sdffg
      DATABASE_URL: postgresql://postgres:pulsar-db-ps@pulsar-postgres:5432/postgres?schema=postgres
      SOCKET_URL: http://138.0.172.170:3001
