
services:

  # database service
  db:
    image: postgres
    container_name: pulsar-postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  # application service
  panel:
    build: "./"
    container_name: pulsar
    restart: always
    volumes:
      - .:/src
    ports:
     - "3000:3000"
    environment:
      ACCESS_TOKEN: g4rren-dansukdfrang
      POOL_TOKEN: g4rren-sdffg
      DATABASE_URL: postgresql://postgres:password@192.168.100.46:5432/postgres?schema=postgres
      SOCKET_URL: http://192.168.100.45:3001
